# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2448db76a7eb8345ee5c52a17f1e1c03da8575560c7deaa0f63e649ba25a1530850dd352a2fd8dd83633206057a8db99c8db2c94903b494c0d686cf3aeddf74b

test:
  secret_key_base: f79a36a9c7fc8f0e79d4903a88a71f53e3a80a4f98a52b96d1921fc29617e2cdf741e9d8ae39cb31896211cd15c001f24ad0308e0421bf9e94033f6235a00585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
